area/ci:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"
    - "install/*"
area/docs:
- changed-files:
  - any-glob-to-any-file:
    - "README.md"
    - "CONTRIBUTING.md"
    - "CONTRIBUTING-gitflow.md"
language/go:
- changed-files:
  - any-glob-to-any-file:
    - "meshsync/*"
    - "internal/**/*"
    - "pkg/**/*"