area/ci:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"
area/models:
- changed-files:
  - any-glob-to-any-file:
    - "pkg/model/**/*"
area/internal:
- changed-files:
  - any-glob-to-any-file:
    - "internal/**/*"
area/meshsync:
- changed-files:
  - any-glob-to-any-file:
    - "meshsync/*"