version: 2

linters-settings:
  cyclop:
    package-average: 7
  govet:
    enable:
      - shadow
      - tests

linters:
  enable-all: false
  disable-all: false
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - unused
    - cyclop

# Add this new section for formatters
formatters:
  enable:
    - gci

issues:
  exclude-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img
