linters-settings:
  # Remove or configure these sections properly
  gci: {}
  goconst: {}
  gocritic: {}
  govet: {}
  cyclop: {}

  # Remove 'unused' or configure it properly
  unused: {}

# Configuration for golangci-lint that is suitable for a Kubernetes operator project built with Golang
linters:
  enable-all: false
  disable-all: false
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - unused
  disable:
    - cyclop
   
# Remove or configure the 'run' section properly
run: {}

issues:
  exclude-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img