version: 2

linters-settings:
  cyclop:
    package-average: 7
  govet:
    enable:
      - shadow
      - tests

linters:
  enable-all: false
  disable-all: false
  enable:
    # Removed gci from here
    - goconst
    - gocritic
    - govet
    - unused
    - cyclop

# Add this new section for formatters
formatters:
  enable:
    - gci
  # Optional: add settings for gci here if needed (e.g., local prefixes, sections, etc.)
  # settings:
  #   gci:
  #     local-prefixes: github.com/your-org/your-project
  #     sections:
  #       - standard
  #       - default
  #       - prefix(github.com/your-org)

issues:
  exclude-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img
