version: 2

linters:
  default: none  # Replaces disable-all/enable-all
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - unused
    - cyclop

linters-settings:
  cyclop:
    package-average: 7
  govet:
    enable:
      - shadow
      - tests

formatters:
  enable:
    - gci

issues:
  exclude-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img
