# linters-settings:
#   gocritic:
#     enabled: true
#     disable:
#       - parallelize
#       - nesting
#       - hugeParam
#       - hugeStruct
#       - nestParam
#       - prealloc
#   govet:
#     enabled: true
#     tests: true
#   shadow:
#     enabled: true
#   golint:
#     enabled: true
#     min-confidence: 0.8
#   scopelint:
#     enabled: true
#     tests: true

version: "2"

# Configuration for golangci-lint that is suitable for a Kubernetes operator project built with Golang
linters:
  enable-all: false
  disable-all: false
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - golint
    - unused
    - cyclop
    - scopelint
  disable:
    - testpackage

run:
  exclude-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img

# issues:
#   exclude-dirs:
#     - vendor
#     - bundle
#     - config
#     - hack
#     - helpers
#     - img
