version: "2"

run:
  skip-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img

linters-settings:
  cyclop:
    package-average: 7
  govet:
    enable:
      - shadow
      - tests

# Configuration for golangci-lint that is suitable for a Kubernetes operator project built with Golang
linters:
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - unused
    - cyclop

issues:
