name: Integration Tests
on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/integration-tests-ci.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/integration-tests-ci.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Install Kind and kubectl
        uses: helm/kind-action@v1.10.0
      - name: Integration tests set up
        run: make integration-tests-setup
      - name: Integration tests run
        run: make integration-tests-run
      - name: Integration tests clean up
        run: make integration-tests-cleanup
      - name: Upload meshsync command output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: meshsync-command-output
          path: integration-tests/*.meshsync-output.txt
          if-no-files-found: warn
