name: Integration Tests
on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
      - "**.golden"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"
      - "**.golden"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: "kind-cluster"
      - name: Create k8s meshery namespace
        run: kubectl create namespace meshery
      - name: Apply k8s resources
        run: |
          kubectl apply -f ./integration-test-yamls/crds.yaml
          kubectl --namespace meshery apply -f ./integration-test-yamls/meshsync.yaml
      - name: Run integration tests
        run: |
          make integration-test
    
