name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-24.04
    steps:
      - name: Drafting release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_PAT }}
